### ISSUE TITLE
Add k8s docs for kms v2alpha1

### ISSUE THREAD

**Issue by ritazh** [aramase/kms#20]
Follow the steps [here](https://kubernetes.io/docs/contribute/new-content/new-features/#open-a-placeholder-pr) to open a PR against dev-1.25 branch in the k/website repo. This PR can be just a placeholder at this time and must be created before August 4.
Refer to [Documenting for a release](https://kubernetes.io/docs/contribute/new-content/new-features/#for-developers-or-other-sig-members) for docs requirements for the release.

**Comment by aramase** [comment]
Closed with https://github.com/kubernetes/website/pull/35046
