### ISSUE TITLE
Support key rotation by updating the proposed v2 proto API

### ISSUE THREAD

**Issue by aramase** [aramase/kms#3]
- With v2alpha1 we're proposing adding a new level of hierarchy with kms plugin using a local KEK to encrypt the data.

Creating this placeholder issue for enhancing envelope encryption to support key rotation

**Comment by enj** [comment]
https://gist.github.com/enj/5307fa9da9b6c476b85b641d1a56db2c

**Comment by enj** [comment]
```sh
$ kubectl get --raw /api/v1 | jq .resources[3]
```

```json
{
  "name": "endpoints",
  "singularName": "",
  "namespaced": true,
  "kind": "Endpoints",
  "verbs": [
    "create",
    "delete",
    "deletecollection",
    "get",
    "list",
    "patch",
    "update",
    "watch"
  ],
  "shortNames": [
    "ep"
  ],
  "storageVersionHash": "fWeeMqaN/OA="
}
```

**Comment by ritazh** [comment]
Closed via https://github.com/kubernetes/enhancements/pull/3302
