### ISSUE TITLE
KAS: update the healthz handler to use the new status API

### ISSUE THREAD

**Issue by enj** [aramase/kms#4]
Currently we build multiple instances of the gRPC service.  The proposed v2 API requires that a single API server process must have a single meaning for the `currentKeyID`.

**Comment by enj** [comment]
I believe @dgrisonnet is going to look into this.

**Comment by ritazh** [comment]
Reducing the scope to update the healthz handler to use the v2 API. This issue depends on the new KMS v2alpha1 to be merged first.

**Comment by enj** [comment]
Closing this as the initial v2 KMS PR covered the healthz handler.
