### ISSUE TITLE
Reference library

### ISSUE THREAD

**Issue by enj** [aramase/kms#6]
1. Key generation for local KEK
2. Rotation based on counter; also rotate once a week even if the counter does not hit 2 million?
3. Encryption using AES-GCM
4. Metrics
5. Logging
6. Externalized encryption of local KEK

**Comment by enj** [comment]
ex of how it is currently happening: https://github.com/aramase/kubernetes-kms/blob/kms-v2alpha1/pkg/kek/kek.go

**Comment by ibihim** [comment]
thx, will work on it.

**Comment by ibihim** [comment]
Created https://github.com/ibihim/kms/commit/2fa84b011d8792dedf12c9d56dd8beff6eb0a2ef, only metric missing.

**Comment by enj** [comment]
Look into making 1,2,3 and 6 optional for cases where a local hardware HSM is used (i.e. PKCS11).

**Comment by ibihim** [comment]
I created a PR, still WIP, but maybe we can split it up in small chunks: https://github.com/aramase/kms/pull/12

I will work on HMS in a different PR.

**Comment by aramase** [comment]
Closing this in favor of https://github.com/kubernetes/kubernetes/issues/112859
